### PR TITLE
Do not try to use host parameters if they doesn't exist

### PR DESCRIPTION
**Pull request by lmesz**
It is just a small fix to handle when host get unvalid data

### CODE REVIEW

**Comment by lmesz** [comment]
Maybe I missunderstand something, but on this path InvalidInputDataException is the proper exception. I think HostExists is misleading, because in this path one of the mandatory field is missing. The exception that I get previously doesn't thrown by db,  but by python.
So I think I have to create az invalidInputDataException and throw it when one of the mandatory field is missing and put the whole part into a try catch and catch the db exception. (Duplicate host, etc...)
Do you agree ?

**Comment by talien** [comment]
I'm sorry I misunderstood the commit message. Then 400 should be fine, with a result in JSON which mandatory field is missing.

**Comment by wuxort** [comment]
Or maybe an insuffictientInputDataException, because it can't be invalid which isn't there.

**Comment by lmesz** [comment]
Agree I fix it I hope at afternoon or late afternoon.

**Comment by lmesz** [comment]
And yes the commit message is misleading

**Comment by talien** [comment]
Well, maybe i'll open wide the door to a good flame with my remark, but if you see the resource as a whole, then either missing parts or parts not conform to a predefined schema invalidate the whole resource. So from this perspective, there is no such thing as missing parts of a resource.

**Comment by lmesz** [comment]
Updated based on the comments. PTAL

**Pull request merged**
